import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { getDetailsForUUID, submitLink } from "../client/api-client";
import { resourceLimits } from "worker_threads";

const inter = Inter({ subsets: ["latin"] });

export default function Transcription() {
  const [link, setLink] = useState<string>("");
  const [submitted, setSubmitted] = useState<boolean>(false);
  const [listenID, setListenID] = useState<any>(null); // TODO: type this

  const listenForResults = (id: string) => {
    console.log("listening for results");
    if (!id) return;
    console.log("have uuid");
    console.log("sending request");
    getDetailsForUUID(id).then((data) => {
      if (data["result"]) {
        console.log("have data", data);
        clearInterval(listenID); // TODO (param): this isn't working rn for some reason
      }
    });
  };

  const submit = () => {
    if (!link.includes("youtube.com")) {
      alert("not a youtube link, try again!");
      return;
    }

    setSubmitted(true);
    submitLink(link).then((data) => {
      console.log("submitted successfully!", data);
      console.log(data.id);
      const id = setInterval(() => listenForResults(data.id), 5 * 1000);
      setListenID(id);
    });
  };

  return (
    <>
      <Head>
        <title>transcribe</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <h2>Youtube link</h2>
          <input type="text" onChange={(e) => setLink(e.target.value)} />
          <br />
          <input type="button" onClick={(e) => submit()} value="Submit" />
          {submitted && <p>Submitted, please wait for results!</p>}
        </div>
      </main>
    </>
  );
}
